'use client';

/**
 * Renders the redacted shared payload with the SAME components the merchant
 * sees — runId is never passed, so every action affordance (drafts, deck
 * export, share) is absent by construction; the reader gets the full story,
 * none of the controls.
 */

import { useEffect, useState } from 'react';

import { API_CONFIG } from '@/lib/config';
import { AuditScoreStrip, AuditScoreStripFooter } from '@/components/audit/AuditScoreStrip';
import { ShareOfVoiceBars } from '@/components/audit/ShareOfVoiceBars';
import { MerchantNarrativePanel } from '@/components/audit/MerchantNarrativePanel';
import { PrioritizedActionsPanel } from '@/components/audit/PrioritizedActionsPanel';
import { PerSkuReportCard } from '@/components/audit/PerSkuReportCard';
import { SurfaceCard } from '@/components/ui/merchant-primitives';
import { summaryRenderable } from '@/lib/audit/reportSummary';
import type { UrlReadinessAuditResponse } from '@/lib/types/ai-readiness';

type State = 'loading' | 'gone' | 'ready';

export function SharedAuditClient({ token }: { token: string }) {
  const [state, setState] = useState<State>('loading');
  const [data, setData] = useState<UrlReadinessAuditResponse | null>(null);

  useEffect(() => {
    let cancelled = false;
    fetch(`${API_CONFIG.BASE_URL}/api/public/audit-share/${encodeURIComponent(token)}`)
      .then(async (res) => {
        if (cancelled) return;
        if (!res.ok) {
          setState('gone');
          return;
        }
        setData((await res.json()) as UrlReadinessAuditResponse);
        setState('ready');
      })
      .catch(() => {
        if (!cancelled) setState('gone');
      });
    return () => {
      cancelled = true;
    };
  }, [token]);

  if (state === 'loading') {
    return <p className="merchant-text-muted px-6 py-16 text-center text-sm">Loading shared report…</p>;
  }
  if (state === 'gone' || !data) {
    return (
      <div className="px-6 py-16 text-center">
        <h1 className="text-lg font-semibold">This shared report isn&apos;t available</h1>
        <p className="merchant-text-muted mt-1 text-sm">
          The link may have expired or been revoked by the brand.
        </p>
      </div>
    );
  }

  const summary = data.report_summary ?? null;
  const perSku = data.per_sku_reports ?? [];

  return (
    <div className="mx-auto max-w-5xl space-y-4 px-4 py-8">
      <p className="merchant-text-muted text-xs">
        Shared read-only report · generated by{' '}
        <a href="https://pivota.cc" className="underline">Pivota</a> AI-visibility audit
      </p>
      <SurfaceCard strong>
        {summary && summaryRenderable(summary) ? (
          <>
            <AuditScoreStrip summary={summary} runId={null} />
            <AuditScoreStripFooter summary={summary} />
            <ShareOfVoiceBars summary={summary} />
          </>
        ) : null}
      </SurfaceCard>
      <MerchantNarrativePanel narrative={data.merchant_narrative} />
      <PrioritizedActionsPanel
        actions={data.merchant_narrative?.prioritized_actions}
        runId={null}
      />
      <div className="space-y-3">
        {perSku.map((r, i) => (
          <PerSkuReportCard
            key={r.sku_key || i}
            report={r}
            index={i}
            catalogDimensionsAvailable={false}
            runId={null}
            pdpUrl={null}
          />
        ))}
      </div>
    </div>
  );
}
