'use client';

/**
 * Renders the redacted shared payload with the SAME components the merchant
 * sees — runId is never passed, so every action affordance (drafts, deck
 * export, share) is absent by construction; the reader gets the full story,
 * none of the controls.
 */

import { useEffect, useState } from 'react';

import { API_CONFIG } from '@/lib/config';
import { AuditScoreStrip, AuditScoreStripFooter } from '@/components/audit/AuditScoreStrip';
import { ShareOfVoiceBars } from '@/components/audit/ShareOfVoiceBars';
import { EngineDiscoverySplitChart } from '@/components/audit/EngineDiscoverySplitChart';
import { MomentumCard } from '@/components/audit/MomentumCard';
import { ReportSectionBoundary } from '@/components/audit/ReportSectionBoundary';
import { MerchantNarrativePanel } from '@/components/audit/MerchantNarrativePanel';
import { PrioritizedActionsPanel } from '@/components/audit/PrioritizedActionsPanel';
import { GetCitedPanel } from '@/components/audit/GetCitedPanel';
import { PerSkuReportCard } from '@/components/audit/PerSkuReportCard';
import { SurfaceCard } from '@/components/ui/merchant-primitives';
import { summaryRenderable } from '@/lib/audit/reportSummary';
import type { UrlReadinessAuditResponse } from '@/lib/types/ai-readiness';

type State = 'loading' | 'gone' | 'ready';

export function SharedAuditClient({ token }: { token: string }) {
  const [state, setState] = useState<State>('loading');
  const [data, setData] = useState<UrlReadinessAuditResponse | null>(null);

  useEffect(() => {
    let cancelled = false;
    fetch(`${API_CONFIG.BASE_URL}/api/public/audit-share/${encodeURIComponent(token)}`)
      .then(async (res) => {
        if (cancelled) return;
        if (!res.ok) {
          setState('gone');
          return;
        }
        setData((await res.json()) as UrlReadinessAuditResponse);
        setState('ready');
      })
      .catch(() => {
        if (!cancelled) setState('gone');
      });
    return () => {
      cancelled = true;
    };
  }, [token]);

  if (state === 'loading') {
    return <p className="merchant-text-muted px-6 py-16 text-center text-sm">Loading shared report…</p>;
  }
  if (state === 'gone' || !data) {
    return (
      <div className="px-6 py-16 text-center">
        <h1 className="text-lg font-semibold">This shared report isn&apos;t available</h1>
        <p className="merchant-text-muted mt-1 text-sm">
          The link may have expired or been revoked by the brand.
        </p>
      </div>
    );
  }

  const summary = data.report_summary ?? null;
  const perSku = data.per_sku_reports ?? [];

  // Same derivations as the authed results page (url-audit/page.tsx), minus
  // brand_report (not in the share allowlist) — the summary subject carries
  // the merchant name instead. runId stays null, so every action affordance
  // (draft outreach, tracked tasks) is absent by construction; the reader
  // gets the channels + how-to-get-cited guidance, none of the controls.
  const authHosts =
    (data.authority_map as { hosts?: { host: string; providers?: string[] }[] } | undefined)
      ?.hosts ?? [];
  const enginesByHost: Record<string, string[]> = {};
  for (const h of authHosts) {
    if (h?.host) enginesByHost[h.host] = h.providers ?? [];
  }
  const enginePlaybook = perSku[0]?.engine_playbook ?? null;
  const categoryHint =
    perSku[0]?.product_competitiveness?.discovery?.missed?.[0] ??
    enginePlaybook?.divergence?.[0]?.query ??
    null;
  const redditSubreddits = (
    (data.authority_map as { skus?: { reddit?: { subreddits?: unknown[] } }[] } | undefined)
      ?.skus ?? []
  ).flatMap((s) => s?.reddit?.subreddits ?? []);

  return (
    <div className="mx-auto max-w-5xl space-y-4 px-4 py-8">
      <p className="merchant-text-muted text-xs">
        Shared read-only report · generated by{' '}
        <a href="https://pivota.cc" className="underline">Pivota</a> AI-visibility audit
      </p>
      <SurfaceCard strong>
        {summary && summaryRenderable(summary) ? (
          <>
            <AuditScoreStrip summary={summary} runId={null} />
            <AuditScoreStripFooter summary={summary} />
            <ShareOfVoiceBars summary={summary} />
          </>
        ) : null}
      </SurfaceCard>
      {/* Same chart pair as the authed report (#189/#191), same position —
          overview payoff before the narrative. The share payload carries the
          momentum data inline (visibility_tracking + prior_brand_dimensions),
          so neither chart ever calls an authed endpoint; each self-hides
          without data. */}
      <ReportSectionBoundary section="share-engine-split" silent>
        <EngineDiscoverySplitChart reports={perSku} />
      </ReportSectionBoundary>
      <ReportSectionBoundary section="share-momentum" silent>
        <MomentumCard
          rollup={data.brand_rollup}
          currentRunId={null}
          subjectType="merchant_url"
          tracking={data.visibility_tracking ?? null}
          priorDimensions={data.prior_brand_dimensions ?? null}
        />
      </ReportSectionBoundary>
      <MerchantNarrativePanel narrative={data.merchant_narrative} />
      <PrioritizedActionsPanel
        actions={data.merchant_narrative?.prioritized_actions}
        runId={null}
      />
      <GetCitedPanel
        moves={data.where_youre_losing?.outreach_moves}
        pitchTargets={data.where_youre_losing?.pitch_targets}
        closedChannels={data.where_youre_losing?.closed_channels}
        closedChannelsNote={data.where_youre_losing?.closed_channels_note}
        enginesByHost={enginesByHost}
        enginePlaybook={enginePlaybook}
        categoryHint={categoryHint}
        brand={summary?.subject?.merchant_name ?? null}
        runId={null}
        redditSubreddits={redditSubreddits as Parameters<typeof GetCitedPanel>[0]['redditSubreddits']}
      />
      <div className="space-y-3">
        {perSku.map((r, i) => (
          <PerSkuReportCard
            key={r.sku_key || i}
            report={r}
            index={i}
            catalogDimensionsAvailable={false}
            runId={null}
            pdpUrl={null}
          />
        ))}
      </div>
    </div>
  );
}
